server:
  port: 8888

spring:
  application:
    name: configuration-service
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
      discovery:
        enabled: true
        service-id: configuration-service
    service-registry:
      auto-registration:
        enabled: true

eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
  client:
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://service-discovery:8761/eureka}
    enabled: true
    register-with-eureka: true