FROM gcr.io/distroless/java17-debian11
MAINTAINER www.mryakar.me
COPY target/configuration-service-1.0.0.jar configuration-service-1.0.0.jar
ENTRYPOINT ["java","-jar","/configuration-service-1.0.0.jar"]